"""Minor fixes

Revision ID: 2b8951072aaf
Revises: 4f7cde89002a
Create Date: 2024-10-26 22:32:55.129077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b8951072aaf'
down_revision: Union[str, None] = '4f7cde89002a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_assignation', sa.Column('achievement_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'achievement_assignation', 'achievement', ['achievement_id'], ['id'])
    op.add_column('challenge', sa.Column('prize_determination_fn', sa.Enum('HIGHER_THAN', 'LESS_THAN', 'HEAD', 'TAIL', name='selectionfnenum'), nullable=False))
    op.drop_column('challenge', 'prize_delermination_fn')
    op.alter_column('space', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('phone_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.alter_column('space', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('challenge', sa.Column('prize_delermination_fn', postgresql.ENUM('HIGHER_THAN', 'LESS_THAN', 'HEAD', 'TAIL', name='selectionfnenum'), autoincrement=False, nullable=False))
    op.drop_column('challenge', 'prize_determination_fn')
    op.drop_constraint(None, 'achievement_assignation', type_='foreignkey')
    op.drop_column('achievement_assignation', 'achievement_id')
    # ### end Alembic commands ###
