"""dev

Revision ID: 495bdfb40d1d
Revises: 3e26d044e226
Create Date: 2024-10-27 09:58:30.029521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495bdfb40d1d'
down_revision: Union[str, None] = '3e26d044e226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_member', sa.Column('cached_aggregated_result', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_member', 'cached_aggregated_result')
    # ### end Alembic commands ###
