"""Fix typo

Revision ID: 4f7cde89002a
Revises: 866ba12cad61
Create Date: 2024-10-26 21:48:19.100415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7cde89002a'
down_revision: Union[str, None] = '866ba12cad61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('prize_delermination_fn', sa.Enum('HIGHER_THAN', 'LESS_THAN', 'HEAD', 'TAIL', name='selectionfnenum'), nullable=False))
    op.drop_column('challenge', 'prize_determinataion_fn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('prize_determinataion_fn', postgresql.ENUM('HIGHER_THAN', 'LESS_THAN', 'HEAD', 'TAIL', name='selectionfnenum'), autoincrement=False, nullable=False))
    op.drop_column('challenge', 'prize_delermination_fn')
    # ### end Alembic commands ###
