"""uniq constraints for members

Revision ID: b783115aca12
Revises: 495bdfb40d1d
Create Date: 2024-10-27 10:37:46.893334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b783115aca12'
down_revision: Union[str, None] = '495bdfb40d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'challenge_member', ['user_id', 'challenge_id'])
    op.create_unique_constraint(None, 'space_member', ['user_id', 'space_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space_member', type_='unique')
    op.drop_constraint(None, 'challenge_member', type_='unique')
    # ### end Alembic commands ###
