"""members_count

Revision ID: f81b37895dec
Revises: b3d1ca374ca8
Create Date: 2024-10-27 00:34:36.470780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f81b37895dec'
down_revision: Union[str, None] = 'b3d1ca374ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge', 'ends_at_determination_fn',
               existing_type=postgresql.ENUM('HIGHER_THAN', 'LESS_THAN', 'HEAD', 'TAIL', name='selectionfnenum'),
               nullable=True)
    op.add_column('space', sa.Column('members_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'members_count')
    op.alter_column('challenge', 'ends_at_determination_fn',
               existing_type=postgresql.ENUM('HIGHER_THAN', 'LESS_THAN', 'HEAD', 'TAIL', name='selectionfnenum'),
               nullable=False)
    # ### end Alembic commands ###
